apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
 # namespace: probe-demo
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
#        livenessProbe:
#          exec:
#            command:
#            - ls
#            - /usr/share/nginx/html/index.html
